### ISSUE TITLE
Definition for 'fw_typ'

### ISSUE THREAD

**Issue by larswaechter** [VerkehrsbetriebeZuerich/ogd_examples_python#1]
Hello there!

In the dataset 'Fahrzeiten der VBZ im SOLL-IST-Vergleich' there is a column called Fahrwegtyp (fw_typ). Do you have an overview of the encoded values' definitions? Am I right, that the value represents the type of the vehicle? Like 1=Tram; 2=Bus ... for example.

Thanks in advance.

**Comment by yananeuenschwander** [comment]
Hello,

Thank you for your question regarding the dataset "Fahrzeiten der VBZ im SOLL-IST-Vergleich." The column "Fahrwegtyp" (fw_typ) refers to the trip pattern type. The encoded values are as follows:
1 = normal (German: Normalfahrt)
2 = pull out (Ausfahrt)
3 = pull in (Einfahrt)
4 = extra trip (Zusatzfahrt)

We are planning to update this information on the Open Data Zurich webpage shortly.

If you have any further questions or need additional details about the dataset, please don’t hesitate to reach out.

Best regards,
Yana
