### ISSUE TITLE
Missing data input in example_traveltimedata.py

### ISSUE THREAD

**Issue by antonindanalet** [VerkehrsbetriebeZuerich/ogd_examples_python#7]
In https://github.com/VerkehrsbetriebeZuerich/ogd_examples_python/blob/main/05_Skripte/example_traveltimedata.py, line 40, the code reads a CSV file, `fahrzeiten_soll_ist_20200809_20200815.csv`. This code does not exist, at least not for all years (I've downloaded 2023).

Same problem with 
```
haltepunkt = pd.read_csv("haltepunkt.csv")
haltestelle = pd.read_csv("haltestelle.csv")
```

**Comment by yananeuenschwander** [comment]
I updated the scripts and the readme. The travel time datasets are no longer grouped under a single category with files for each year. Instead, they are now available as individual datasets for each year (e.g., https://data.stadt-zuerich.ch/dataset?q=Fahrzeiten+2020+der+VBZ+im+SOLL-IST-Vergleich+%28Nachf%C3%BChrung+eingestellt%29). Additionally, these datasets are no longer maintained on OGD. I updated this information in the script as well.
